Repository helldivers-2/api, pull requests merged in 2024-04, with the labels that each got.

#36 use relative URL
  src/Helldivers-2-API/wwwroot/redoc.html
  src/Helldivers-2-API/wwwroot/swagger-ui.html
Labels: bug

#37 Docs/fix spelling
  src/Helldivers-2-API/wwwroot/Helldivers-2-API.json
  src/Helldivers-2-API/wwwroot/Helldivers-2-API_arrowhead.json
  src/Helldivers-2-Models/ArrowHead/Assignments/Task.cs
  src/Helldivers-2-Models/ArrowHead/WarStatus.cs
Labels: documentation

#39 fix: pass in `maxEntries` parameter to NewsFeed
  src/Helldivers-2-Core/Facades/V1Facade.cs
  src/Helldivers-2-Sync/Services/ArrowHeadApiService.cs
Labels: bug

#40 docs: add Fly server to swagger
  src/Helldivers-2-API/OpenApi/HelldiversDocumentProcessor.cs
  src/Helldivers-2-API/Program.cs
  src/Helldivers-2-API/wwwroot/Helldivers-2-API.json
Labels: documentation

#42 Make raw endpoints future-proof
  src/Helldivers-2-API/Controllers/ArrowHeadController.cs
  src/Helldivers-2-API/appsettings.json
  src/Helldivers-2-API/wwwroot/Helldivers-2-API.json
  src/Helldivers-2-API/wwwroot/Helldivers-2-API_arrowhead.json
  src/Helldivers-2-Core/Extensions/ServiceCollectionExtensions.cs
  src/Helldivers-2-Core/Facades/ArrowHeadFacade.cs
  src/Helldivers-2-Core/Localization/CultureDictionary.cs
  src/Helldivers-2-Core/Storage/ArrowHead/ArrowHeadStore.cs
  src/Helldivers-2-Core/Storage/ArrowHead/AssignmentStore.cs
  src/Helldivers-2-Core/Storage/ArrowHead/NewsFeedStore.cs
  src/Helldivers-2-Core/Storage/ArrowHead/WarIdStore.cs
  src/Helldivers-2-Core/Storage/ArrowHead/WarInfoStore.cs
  src/Helldivers-2-Core/Storage/ArrowHead/WarStatusStore.cs
  src/Helldivers-2-Core/Storage/ArrowHead/WarSummaryStore.cs
  src/Helldivers-2-Core/StorageFacade.cs
  src/Helldivers-2-Sync/Hosted/ArrowHeadSyncService.cs
  src/Helldivers-2-Sync/Services/ArrowHeadApiService.cs
Labels: feature request

#45 Map PlanetEvent MaxHealth
  src/Helldivers-2-API/wwwroot/Helldivers-2-API.json
  src/Helldivers-2-API/wwwroot/Helldivers-2-API_arrowhead.json
  src/Helldivers-2-Core/Mapping/V1/PlanetMapper.cs
  src/Helldivers-2-Models/ArrowHead/Status/PlanetEvent.cs
  src/Helldivers-2-Models/V1/Planets/Event.cs
Labels: bug

#49 Add factions data
  src/Helldivers-2-API/wwwroot/Helldivers-2-API.json
  src/Helldivers-2-API/wwwroot/Helldivers-2-API_arrowhead.json
  src/Helldivers-2-Core/Mapping/V1/WarMapper.cs
Labels: bug

#54 Update README.md
  README.md
Labels: documentation

#57 fix rate limits
  fly.toml
  src/Helldivers-2-API/Program.cs
Labels: bug

#52 DocFX documentation
  .github/workflows/pages.yml
  .gitignore
  Helldivers-2.sln
  docfx.json
  docs/getting-started.md
  docs/introduction.md
  docs/openapi/redoc.html
  docs/openapi/swagger-ui.html
  docs/toc.yml
  index.md
  src/Helldivers-2-API/Helldivers-2-API.csproj
  src/Helldivers-2-API/Program.cs
  src/Helldivers-2-API/wwwroot/Helldivers-2-API.json
  src/Helldivers-2-API/wwwroot/Helldivers-2-API_arrowhead.json
  toc.yml
Labels: documentation, feature request

#63 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation

#66 setup code owners
  .github/CODEOWNERS
  Helldivers-2.sln
Labels: documentation

#65 Map PlanetAttacks to Planets
  src/Helldivers-2-Core/Mapping/V1/PlanetMapper.cs
  src/Helldivers-2-Models/V1/Planet.cs
Labels: mapping

#73 Document containers
  docs/containers.md
  docs/toc.yml
  src/Helldivers-2-API/Dockerfile
  src/Helldivers-2-API/Program.cs
  toc.yml
Labels: documentation

#79 account for gametime drift
  src/Helldivers-2-Core/Facades/V1Facade.cs
  src/Helldivers-2-Core/Mapping/MappingContext.cs
  src/Helldivers-2-Core/Mapping/V1/AssignmentMapper.cs
  src/Helldivers-2-Core/Mapping/V1/CampaignMapper.cs
  src/Helldivers-2-Core/Mapping/V1/DispatchMapper.cs
  src/Helldivers-2-Core/Mapping/V1/PlanetMapper.cs
  src/Helldivers-2-Core/Mapping/V1/WarMapper.cs
  src/Helldivers-2-Core/StorageFacade.cs
Labels: bug, mapping

#81 Allow LocalizedMessage to return all messages
  src/Helldivers-2-API/OpenApi/DocumentProcessors/ArrowHeadDocumentProcessor.cs
  src/Helldivers-2-API/OpenApi/DocumentProcessors/HelldiversDocumentProcessor.cs
  src/Helldivers-2-API/OpenApi/TypeMappers/LocalizedMessageTypeMapper.cs
  src/Helldivers-2-API/Program.cs
  src/Helldivers-2-Models/Domain/Localization/LocalizedMessage.cs
  src/Helldivers-2-Models/Domain/Localization/LocalizedMessageConverter.cs
Labels: feature request, PR ready, mapping

#80 Feature/rate limits
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
  docs/containers.md
  src/Helldivers-2-API/Configuration/ApiConfiguration.cs
  src/Helldivers-2-API/Configuration/AuthenticationConfiguration.cs
  src/Helldivers-2-API/Controllers/DevelopmentController.cs
  src/Helldivers-2-API/Extensions/ClaimsPrincipalExtensions.cs
  src/Helldivers-2-API/Helldivers-2-API.csproj
  src/Helldivers-2-API/Middlewares/RateLimitMiddleware.cs
  src/Helldivers-2-API/OpenApi/DocumentProcessors/HelldiversDocumentProcessor.cs
  src/Helldivers-2-API/Program.cs
  src/Helldivers-2-API/appsettings.Development.json
  src/Helldivers-2-API/appsettings.json
Labels: documentation, feature request

#87 export metrics to Prometheus
  Directory.Build.props
  fly.toml
  src/Helldivers-2-API/Helldivers-2-API.csproj
  src/Helldivers-2-API/Program.cs
  src/Helldivers-2-Sync/Hosted/ArrowHeadSyncService.cs
  src/Helldivers-2-Sync/Hosted/SteamSyncService.cs
Labels: feature request

#92 adds endpoint for `/`
  src/Helldivers-2-API/OpenApi/DocumentProcessors/HelldiversDocumentProcessor.cs
  src/Helldivers-2-API/Program.cs
  src/Helldivers-2-API/Properties/launchSettings.json
Labels: documentation, feature request

#93 Update fly.toml
  fly.toml
Labels: bug, documentation, PR ready

#95 metrics improvement
  README.md
  src/Helldivers-2-API/Metrics/ClientMetric.cs
  src/Helldivers-2-API/Middlewares/RedirectFlyDomainMiddleware.cs
  src/Helldivers-2-API/Program.cs
  src/Helldivers-2-Sync/Hosted/ArrowHeadSyncService.cs
  src/Helldivers-2-Sync/Hosted/SteamSyncService.cs
  src/Helldivers-2-Sync/Services/ArrowHeadApiService.cs
Labels: documentation, feature request
