Repository helldivers-2/api, pull requests merged in 2024-11, with the labels that each got.

#115 Add headers to health check in fly.toml
  fly.toml
Labels: bug

#117 Add SuperHeadersProcessor to OpenApi
  Helldivers-2.sln
  src/Helldivers-2-API/OpenApi/OperationProcessors/SuperHeadersProcessor.cs
  src/Helldivers-2-API/Program.cs
Labels: bug, documentation

#121 move Prometheus endpoints to before rate limiting middleware
  src/Helldivers-2-API/Program.cs
Labels: bug, dependencies

#119 Update to .NET 9.0 and associated packages
  .github/workflows/dotnet.yml
  .github/workflows/pages.yml
  Directory.Build.props
  src/Helldivers-2-API/Dockerfile
  src/Helldivers-2-API/Helldivers-2-API.csproj
  src/Helldivers-2-Core/Helldivers-2-Core.csproj
  src/Helldivers-2-SourceGen/Helldivers-2-SourceGen.csproj
  src/Helldivers-2-Sync/Helldivers-2-Sync.csproj
Labels: feature request, PR ready, dependencies

#120 add SpaceStation to ArrowHead API
  src/Helldivers-2-Core/Extensions/ServiceCollectionExtensions.cs
  src/Helldivers-2-Core/Facades/V1Facade.cs
  src/Helldivers-2-Core/Mapping/V1/SpaceStationMapper.cs
  src/Helldivers-2-Core/Storage/V1/SpaceStationStore.cs
  src/Helldivers-2-Models/ArrowHead/Status/SpaceStation.cs
  src/Helldivers-2-Models/ArrowHead/WarStatus.cs
  src/Helldivers-2-Models/V1/SpaceStation.cs
Labels: documentation, feature request, PR ready, mapping

#124 add routing for space station endpoints added in #120
  src/Helldivers-2-API/Controllers/V1/SpaceStationController.cs
  src/Helldivers-2-API/Program.cs
Labels: bug, mapping

#125 change KeyValuePairs in generated code to primitive arrays
  src/Helldivers-2-Models/Domain/Localization/LocalizedMessage.cs
  src/Helldivers-2-SourceGen/Parsers/PlanetsParser.cs
Labels: bug, dependencies

#126 Various bug fixes
  .github/workflows/pages.yml
  Helldivers-2.sln
  src/Helldivers-2-API/Controllers/V1/SpaceStationController.cs
  src/Helldivers-2-API/Middlewares/RateLimitMiddleware.cs
  src/Helldivers-2-Models/V1SerializerContext.cs
Labels: bug, dependencies

#127 Fix outdated API spec links in README
  README.md
Labels: bug, documentation
